global:
  resolve_timeout: 1m

route:
  receiver: 'webhook_receiver'

receivers:
  - name: 'webhook_receiver'
    webhook_configs:
      - url: 'https://webhook.site/decbab54-6b80-4770-a16c-547b48eb0f6d'
